name: Generate IPA

on:
  workflow_dispatch:
  push:
    branches:
      - develop

jobs:
 build:
    name: Build and Test default scheme using iPhone simulator
    runs-on: macos-26

    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install and run 'bundle install'
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
          # runs 'bundle install' and caches installed gems automatically
          bundler-cache: true
      - name: Install npm
        uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: Setup .mapbox file with MAPBOX_DOWNLOAD_TOKEN
        run: echo $MAPBOX_DOWNLOAD_TOKEN >> ~/.mapbox
        env:
          MAPBOX_DOWNLOAD_TOKEN: ${{ secrets.MAPBOX_DOWNLOAD_TOKEN }}
      - name: Setup .netrc with MAPBOX_DOWNLOAD_TOKEN
        run: |
          echo 'machine api.mapbox.com' >> ~/.netrc
          echo 'login mapbox' >> ~/.netrc
          echo "password $MAPBOX_DOWNLOAD_TOKEN" >> ~/.netrc
          chmod 0600 ~/.netrc
        env:
          MAPBOX_DOWNLOAD_TOKEN: ${{ secrets.MAPBOX_DOWNLOAD_TOKEN }}
      - name: Set Xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with: 
          xcode-version: '26.3'
      - name: Install Firebase CLI
        if: success()
        run: npm install -g firebase-tools
      - name: Setup Firebase Authentication
        if: success()
        run: |
          echo $FIREBASE_CREDENTIALS_JSON >> firebase-credentials.json
          export GOOGLE_APPLICATION_CREDENTIALS="firebase-credentials.json"
          cat firebase-credentials.json
          echo $GOOGLE_APPLICATION_CREDENTIALS
        env:
          FIREBASE_CREDENTIALS_JSON: ${{ secrets.FIREBASE_CREDENTIALS_JSON }}
      - name: Create Release Notes File
        if: success()
        run: |
          cat > release_notes.txt << 'EOF'
          ${{ steps.release_notes.outputs.commits }}
          Build: ${{ github.run_number }} | Branch: ${{ github.ref_name }} | Triggered by: ${{ github.actor }}
          EOF
      - name: Check if firebase logged in correctly
        if: success()
        run: |
          firebase login:ci
          firebase projects:list